In [1]:
import torch
import numpy as np

print(f"Is GPU available? {torch.cuda.is_available()}")
print(f"PyTorch version: {torch.__version__}")

Is GPU available? True
PyTorch version: 2.8.0+cu128


### Tensors

In [2]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2, 3])
tensor2d = torch.tensor([[1, 2],
                         [3, 4]])
tensor3d = torch.tensor([[[1, 2], [3, 4]],
                         [[5, 6], [7, 8]]])

nptensor = np.array([[1, 2], [3, 4]])
tensorfromnumpy = torch.from_numpy(nptensor)

print(tensorfromnumpy)

print("Number of tensors' dimensions:")
print(tensor0d.ndim)
print(tensor1d.ndim)
print(tensor2d.ndim)
print(tensor3d.ndim)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
Number of tensors' dimensions:
0
1
2
3


In [3]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print("Tensors datatypes:")
print(floatvec.dtype)
print(floatvec.to(torch.int64).dtype)

Tensors datatypes:
torch.float32
torch.int64


In [4]:
print(tensorfromnumpy.shape)
floatvec.shape

torch.Size([2, 2])


torch.Size([3])

In [5]:
tensor = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
print(tensor)
tensor_reshaped = tensor.reshape(3, 2)
print(tensor_reshaped)
print(tensor.view(3, 2))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [6]:
print(torch.matmul(tensor, tensor.T))
print(tensor @ tensor.T)

tensor([[14, 32],
        [32, 77]])
tensor([[14, 32],
        [32, 77]])


### Autograd

In [9]:
from torch.nn import functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.0])
w1 = torch.tensor([2.0], requires_grad=True)
b1 = torch.tensor([-1.0], requires_grad=True)

z1 = x1 * w1 + b1
a1 = torch.sigmoid(z1)
loss = F.binary_cross_entropy(a1, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b1 = grad(loss, b1, retain_graph=True)

print(f"Gradient of loss w.r.t w1: {grad_L_w1}")
print(f"Gradient of loss w.r.t b1: {grad_L_b1}")

Gradient of loss w.r.t w1: (tensor([-0.2689]),)
Gradient of loss w.r.t b1: (tensor([-0.2689]),)


In [10]:
loss.backward(retain_graph=True)
print(w1.grad)
print(b1.grad)

tensor([-0.2689])
tensor([-0.2689])
